on:
  push:
    paths:
      - 'firmware/**'
      - '.github/workflows/build-firmware.yml'
  pull_request:
    paths:
      - 'firmware/**'
      - '.github/workflows/build-firmware.yml'
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: firmware/build.yaml
      config_path: firmware
